cyl_residuos/routes/web.php
Route::pattern('slug', '[a-z0-9- _]+');

Route::group(['prefix' => 'admin', 'namespace'=>'Admin'], function () {

  # páginas de error que se deben mostrar sin necesidad de iniciar sesión
    Route::get('404', function () {
        return view('admin/404');
    });

    Route::get('500', function () {
        return view('admin/500');
    });
    # Lock screen
    Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
    Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');
    # RUTAS BÁSICAS
    Route::get('login', 'AuthController@getSignin')->name('login');
    Route::get('signin', 'AuthController@getSignin')->name('signin');
    Route::post('signin', 'AuthController@postSignin')->name('postSignin');
   // Route::post('signup', 'AuthController@postSignup')->name('admin.signup');
    Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password');
    # Forgot Password Confirmation
    Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
    Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

    # Logout
    Route::get('logout', 'AuthController@getLogout')->name('logout');

    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
});



// RUTAS ESPECIALES PARA EL ADMINISTRADOR



Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    # GUI Crud Generator
    Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('generator_builder');
    Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');
    Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');
    // Model checking
    Route::post('modelCheck', 'ModelcheckController@modelCheck');

    # Dashboard / Index
    Route::get('/', 'JoshController@showHome')->name('dashboard');
    # crop demo
    Route::post('crop_demo', 'JoshController@crop_demo')->name('crop_demo');
    //Log viewer routes
  

 
    # Activity log
    Route::get('activity_log/data', 'JoshController@activityLogData')->name('activity_log.data');
//    Route::get('/', 'JoshController@index')->name('index');
});









Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {

    # GESTIÓN DE USUARIOS
    Route::group([ 'prefix' => 'users'], function () {
        Route::get('data', 'UsersController@data')->name('users.data');
        Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
        Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
        Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
//        Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
        Route::post('passwordreset', 'UsersController@passwordreset')->name('passwordreset');

    });
    Route::resource('users', 'UsersController');

    Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

    # GESTIÓN DE GRUPOS O ROLES
        Route::group(['prefix' => 'groups'], function () {
        Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
        Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
        Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
    });
    Route::resource('groups', 'GroupsController');

   

   
  
    /*routes for file*/
    Route::group(['prefix' => 'file'], function () {
        Route::post('create', 'FileController@store')->name('store');
        Route::post('createmulti', 'FileController@postFilesCreate')->name('postFilesCreate');
        Route::delete('delete', 'FileController@delete')->name('delete');
    });

    Route::get('crop_demo', function () {
        return redirect('admin/imagecropping');
    });



 

 

});


# UPLOADS O CARGA DE MULTIMEDIA

    Route::group(['prefix' => 'uploads', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'UploadController@getModalDelete')->name('uploads.confirm-delete');    
    Route::resource('uploads','UploadController');
    Route::get('uploads/{id}/delete', 'UploadController@getDelete')->name('uploads.delete');  


});

    # GALERIA

    Route::group(['prefix' => 'galeria', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'GaleriaController@getModalDelete')->name('galeria.confirm-delete');    
    Route::resource('galeria','GaleriaController');
    Route::get('galeria/{id}/delete', 'GaleriaController@getDelete')->name('galeria.delete');  


});

    # MENSAJES DE USUARIOS

    Route::group(['prefix' => 'mensajeUsuarios', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'MensajeUsuariosController@getModalDelete')->name('mensajeUsuarios.confirm-delete');    
    Route::resource('mensajeUsuarios','MensajeUsuariosController');
    Route::get('mensajeUsuarios/{id}/delete', 'MensajeUsuariosController@getDelete')->name('mensajeUsuarios.delete');  


});

      # EMPRESAS

    Route::group(['prefix' => 'empresas', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'EmpresaController@getModalDelete')->name('empresas.confirm-delete');    
    Route::resource('empresas','EmpresaController');
    Route::get('empresas/{id}/delete', 'EmpresaController@getDelete')->name('empresas.delete');  


});

  # PROYECTOS

    Route::group(['prefix' => 'proyectos', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'ProyectoController@getModalDelete')->name('proyectos.confirm-delete');    
    Route::resource('proyectos','ProyectoController');
    Route::get('proyectos/{id}/delete', 'ProyectoController@getDelete')->name('proyectos.delete');  


});

      # RESIDUOS

    Route::group(['prefix' => 'residuos', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'ResiduoController@getModalDelete')->name('residuos.confirm-delete');    
    Route::resource('residuos','ResiduoController');
    Route::get('residuos/{id}/delete', 'ResiduoController@getDelete')->name('residuos.delete');  


});


   # RECOLECCIÓN DE RESIDUOS

    Route::group(['prefix' => 'recoleccionResiduos', 'middleware' => 'user'], function () {

  
    Route::get('{id}/confirm-delete', 'Recoleccion_residuoController@getModalDelete')->name('recoleccionResiduos.confirm-delete');    
    Route::resource('recoleccionResiduos','Recoleccion_residuoController');
    Route::get('recoleccionResiduos/{id}/delete', 'Recoleccion_residuoController@getDelete')->name('recoleccionResiduos.delete');  


});


# ESTADISTICAS DE RECOLECCIÓN DE RESIDUOS



     Route::group(['prefix' => 'reportes', 'middleware' => 'cliente'], function () {

        
         Route::get('estadisticas', 'EstadisticasResiduosController@indexestadisticas')->name('estadisticasresiduos');
         Route::get('certificado', 'EstadisticasResiduosController@certificadoIndex')->name('certificado');
         Route::get('reporteexcel', 'EstadisticasResiduosController@reporteexcelIndex')->name('reporteexcel');
         Route::post('certificado', 'EstadisticasResiduosController@certificadopdf')->name('certificadopdf');  
         Route::post('reporteexcel', 'EstadisticasResiduosController@reporteexcel')->name('descargarexcel');       
         Route::get('graficobarras', 'EstadisticasResiduosController@indexestadisticas')->name('graficobarras_get');
         Route::post('graficobarras', 'EstadisticasResiduosController@estadisticasresiduos')->name('graficobarras');

   });






# Las páginas restantes se llamarán desde el método del controlador inferior
# en el escenario del mundo real, es posible que deba definir todas las rutas manualmente

#PAGINAS GENERADAS POR EL CRUD
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('{name?}', 'JoshController@showView');
});





#FrontEndController
Route::get('login', 'FrontEndController@getLogin')->name('login');
Route::post('login', 'FrontEndController@postLogin')->name('login');
//Route::get('register', 'FrontEndController@getRegister')->name('register');
//Route::post('register','FrontEndController@postRegister')->name('register');
//Route::get('activate/{userId}/{activationCode}','FrontEndController@getActivate')->name('activate');
Route::get('forgot-password','FrontEndController@getForgotPassword')->name('forgot-password');
Route::post('forgot-password', 'FrontEndController@postForgotPassword');

# Confirmación al recuperar contraseña 
Route::post('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@postForgotPasswordConfirm');
Route::get('forgot-password/{userId}/{passwordResetCode}', 'FrontEndController@getForgotPasswordConfirm')->name('forgot-password-confirm');







# Mi cuenta mostrar y actualizar información
Route::group(['middleware' => 'user'], function () {
    Route::put('my-account', 'FrontEndController@update');
    Route::get('my-account', 'FrontEndController@myAccount')->name('my-account');
});
Route::get('logout', 'FrontEndController@getLogout')->name('logout');
# contact form

//Route::post('contactenos_send', 'EmailController@postContact')->name('contact');






# RUTAS INDEX 

Route::get('/', 'IndexController@index')->name('home'); 



Route::get('buildingsite','RedireccionController@index')->name('buildingsite_1');
Route::get('contactenos', 'EmailController@index')->name('contactenos');

cyl_residuos/app/Models/Upload.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;



class Upload extends Model
{

    public $table = 'uploads';
    


    public $fillable = [
        'filename',
        'tipo',
        'descripcion',
        'sitio'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'filename' => 'string',
        'tipo' => 'string',
        'descripcion' => 'string',
        'sitio' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tipo' => 'required',
        'descripcion'=>'required'
        
    ];
}

cyl_residuos/resources/views/uploads/crear.blade.php
@extends('layouts.usuarios')

@section('title')
Crear Multimedia
@parent
@stop
 <style type="text/css">
            .btn-file {
                position: relative;
                overflow: hidden;
            }
            .btn-file input[type=file] {
                position: absolute;
                top: 0;
                right: 0;
                min-width: 100%;
                min-height: 100%;
                font-size: 100px;
                text-align: right;
                filter: alpha(opacity=0);
                opacity: 0;
                outline: none;
                background: white;
                cursor: inherit;
                display: block;
            }
        </style>

@section('content')

<section class="content-header">
    <h1>Subir multimedia</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Inicio
            </a>
        </li>
        <li>Uploads</li>
        <li class="active">Crear multimedia </li>
    </ol>
</section>
@include('core-templates::common.errors')
  @include('flash::message')
<section class="content paddingleft_right15">
<div class="row">
 <div class="panel panel-primary">
        <div class="panel-heading">
            <h4 class="panel-title"> <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                Subir archivo
            </h4></div>
        <br />
        <div class="panel-body">
        {!! Form::open(['route' => 'uploads.store', 'method' => 'post', 'files' => true]) !!}

            @include('uploads.fields')

        {!! Form::close() !!}


    </div>
    <br>

  </div>

 </div>

</section>
 @stop
@section('footer_scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $("form").submit(function() {
                $('input[type=submit]').attr('disabled', 'disabled');
                return true;
            });
        });
    </script>
@stop

cyl_residuos/resources/views/uploads/datatables_actions.blade.php
{!! Form::open(['route' => ['uploads.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('.uploads.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('uploads.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

cyl_residuos/resources/views/uploads/edit.blade.php
@extends('layouts.usuarios')

@section('title')
Editar multimedia
@parent
@stop
@section('content')
  @include('core-templates::common.errors')
    <section class="content-header">
     <h1>Uploads Edit</h1>
     <ol class="breadcrumb">
         <li>
             <a href="{{ route('home') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                 Dashboard
             </a>
         </li>
         <li>Uploads</li>
         <li class="active">Edit Upload </li>
     </ol>
    </section>
    <section class="content paddingleft_right15">
      <div class="row">
      <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title"> <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    Edit  Upload
                </h4></div>
            <br />
        <div class="panel-body">
        {!! Form::model($upload, ['route' => ['uploads.update', $upload->id], 'method' => 'patch']) !!}

        @include('uploads.fields')

        {!! Form::close() !!}
        </div>
      </div>
    </div>
   </section>
 @stop
@section('footer_scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $("form").submit(function() {
                $('input[type=submit]').attr('disabled', 'disabled');
                return true;
            });
        });
    </script>
@stop

cyl_residuos/resources/views/uploads/fields.blade.php
<!-- Filename Field -->
<div class="form-group col-sm-12">
 
                      
</div>
<div class="clearfix"></div>

<!-- Tipo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('descripcion', 'Descripción:') !!}
    {!! Form::text('descripcion', null, ['class' => 'form-control','placeholder' => 'Ingrese el nombre del archivo']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('lbltipo', 'Tipo:') !!}
    {!! Form::select('tipo', ['PDF' => 'PDF', 'IMAGEN' => 'IMAGEN', 'WORD' => 'WORD', 'EXCEL' => 'EXCEL','ZIP' => 'ZIP','RAR' => 'RAR','MP3'=>'MP3','POWER POINT PPTX' => 'ARCHIVO POWER POINT PPTX'], null, ['class' => 'form-control','placeholder' => 'Por favor seleccione el tipo de archivo']) !!}
</div>





<div class="form-group col-sm-6">
   {!! Form::label('filename', 'Archivo:') !!}&nbsp;&nbsp;&nbsp; 
                       
<span class="btn btn-default btn-file">
   Seleccione un archivo {!! Form::file('file') !!}
</span>

<br>
<br>
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12 text-center">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('uploads.index') !!}" class="btn btn-default">Cancelar</a>
</div>

cyl_residuos/resources/views/uploads/show.blade.php
@extends('layouts.usuarios')

@section('title')
Ver Multimedia
@parent
@stop

@section('content')
<section class="content-header">
    <h1>Upload View</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Uploads</li>
        <li class="active">Upload View</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
       <div class="panel panel-primary">
        <div class="panel-heading clearfix">
            <h4 class="panel-title"> <i class="livicon" data-name="list-ul" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                Upload details
            </h4>
        </div>
            <div class="panel-body">
                @include('uploads.show_fields')
            </div>
        </div>
    <div class="form-group">
           <a href="{!! route('uploads.index') !!}" class="btn btn-default">Volver</a>
    </div>
  </div>
</section>
@stop

cyl_residuos/resources/views/uploads/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $upload->id !!}</p>
    <hr>
</div>

<!-- Filename Field -->
<div class="form-group">
    {!! Form::label('filename', 'Filename:') !!}
    <p>{!! $upload->filename !!}</p>
    <hr>
</div>

<!-- Tipo Field -->
<div class="form-group">
    {!! Form::label('Tipo', 'Tipo:') !!}
    <p>{!! $upload->tipo !!}</p>
    <hr>
</div>

cyl_residuos/resources/views/uploads/start.blade.php
@extends('layouts.usuarios')

@section('title')
Uploads
@parent
@stop

{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Uploads</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('home') }}"> <i class="livicon" data-name="home" data-size="16" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li>Uploads</li>
        <li class="active">Uploads List</li>
    </ol>
</section>

<section class="content paddingleft_right15">
    <div class="row">
     @include('flash::message')
        <div class="panel panel-primary ">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left"> <i class="livicon" data-name="list-ul" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                    Lista de archivos
                </h4>
                <div class="pull-right">
                    <a href="{{ route('uploads.create') }}" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-plus"></span> @lang('button.create')</a>
                </div>
            </div>
            <br />
            <div class="panel-body table-responsive">
                 @include('uploads.table')
                 
            </div>
        </div>
 </div>
</section>
@stop

cyl_residuos/resources/views/uploads/table.blade.php
<table class="table table-responsive" id="uploads-table" width="100%">
    <thead>
     <tr>
         <th>Consecutivo</th>
                  <th>Creado en</th>
        <th>Nombre Sistema</th>
         <th>URL</th>
        <th>Descripcion</th>
        <th>Tipo</th>
         <th>Sitio</th>
        <th><center>Vista previa</center></th>
        <th >Acción</th>
     </tr>
    </thead>
    <tbody>
    @foreach($uploads as $upload)
        <tr>
             <td>{!! $upload->id!!}</td>
               <td>{!! $upload->created_at!!}</td>

            <td>{!! $upload->filename !!}</td>
             <td>{!! '/uploads/files/'.$upload->filename !!}</td>
            <td>{!! $upload->descripcion !!}</td>
            <td>{!! $upload->tipo !!}</td>
               <td>{!! $upload->sitio !!}</td>
             <td><center><a href="{{asset('/uploads/files/'.$upload->filename)}}" target="_blank">
            <i class="livicon" data-name="external-link" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="editar contenido"></i>
            Visualizar</a></center></td>

            <td>
                 <a href="{{ route('uploads.show', $upload->id) }}">
                     <i class="livicon" data-name="info" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="view upload"></i>
                 </a>
              <!--   <a href="{{ route('uploads.edit', $upload->id) }}">
                     <i class="livicon" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="edit upload"></i>
                 </a> -->
                 <a href="{{ route('uploads.confirm-delete', $upload->id) }}" data-toggle="modal" data-target="#delete_confirm">
                     <i class="livicon" data-name="remove-alt" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete upload"></i>
                 </a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
@section('footer_scripts')

    <div class="modal fade" id="delete_confirm" tabindex="-1" role="dialog" aria-labelledby="user_delete_confirm_title" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>
    <script>$(function () {$('body').on('hidden.bs.modal', '.modal', function () {$(this).removeData('bs.modal');});});</script>
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/buttons.bootstrap.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}"/>
 <link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/buttons.bootstrap.css') }}">
 <script type="text/javascript" src="{{ asset('assets/js/jquery.dataTables.min.js') }}" ></script>
 <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}" ></script>

    <script>
        $('#uploads-table').DataTable({
                      responsive: true,
                      pageLength: 20
                  });
                  $('#uploads-table').on( 'page.dt', function () {
                     setTimeout(function(){
                           $('.livicon').updateLivicon();
                     },500);
                  } );

       </script>

@stop